# Generated by Django 5.2.6 on 2025-09-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='description',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
